parameters:
    ongr_oxid.triggers.action_article.track_fields:
      - OXACTIONID
      - OXOBJECTID
      - OXCLASS

services:
    ongr_oxid.triggers.action_article.create:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxobject2action, C, 1, product, NEW.OXOBJECTID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: action_article_create }

    ongr_oxid.triggers.action_article.delete:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxobject2action, D, 1, product, OLD.OXOBJECTID, [], U]
        tags:
          - { name: ongr_connections.sql_relation, trigger: action_article_delete }

    ongr_oxid.triggers.action_article.update:
        class: %ongr_connections.sql_relations.composed_relation.class%
        arguments: [oxobject2action, U, 1, product, OLD.OXOBJECTID, %ongr_oxid.triggers.action_article.track_fields%]
        tags:
          - { name: ongr_connections.sql_relation, trigger: action_article_update }

