parameters:
    ongr_oxid.triggers.seo.track_fields:
      - OXOBJECTID
      - OXIDENT
      - OXSHOPID
      - OXLANG
      - OXSTDURL
      - OXSEOURL
      - OXTYPE

services:
    # INSERT and UPDATE
    ongr_oxid.triggers.oxseo_update.articles:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=NEW.OXOBJECTID, product, U, 1]

    ongr_oxid.triggers.oxseo_update.category:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcategories, oxcategories.OXID, oxcategories.OXID=NEW.OXOBJECTID, category, U, 1]

    ongr_oxid.triggers.oxseo_update.content:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcontents, oxcontents.OXID, oxcontents.OXID=NEW.OXOBJECTID, content, U, 1]

    # DELETE
    ongr_oxid.triggers.oxseo_delete.articles:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=OLD.OXOBJECTID, product, U, 1]

    ongr_oxid.triggers.oxseo_delete.category:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcategories, oxcategories.OXID, oxcategories.OXID=OLD.OXOBJECTID, category, U, 1]

    ongr_oxid.triggers.oxseo_delete.content:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcontents, oxcontents.OXID, oxcontents.OXID=OLD.OXOBJECTID, content, U, 1]

    # Seo triggers
    ongr_oxid.triggers.oxseo_insert:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxseo, C]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_insert }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_update.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_update.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_update.content]]

    ongr_oxid.triggers.oxseo_update:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxseo, U, %ongr_oxid.triggers.seo.track_fields%]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_oxobjects_update }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_update.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_update.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_update.content]]

    ongr_oxid.triggers.oxseo_delete:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxseo, D]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_delete }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_delete.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_delete.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_delete.content]]
