parameters:
    ongr_oxid.triggers.seo_data.track_fields:
      - OXOBJECTID
      - OXSHOPID
      - OXLANG
      - OXKEYWORDS
      - OXDESCRIPTION
      - OXTIMESTAMP

services:
    # INSERT and UPDATE
    ongr_oxid.triggers.oxseo_data_update.articles:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=NEW.OXOBJECTID, product, U, 1]

    ongr_oxid.triggers.oxseo_data_update.category:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcategories, oxcategories.OXID, oxcategories.OXID=NEW.OXOBJECTID, category, U, 1]

    ongr_oxid.triggers.oxseo_data_update.content:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcontents, oxcontents.OXID, oxcontents.OXID=NEW.OXOBJECTID, content, U, 1]

    # DELETE
    ongr_oxid.triggers.oxseo_data_delete.articles:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxarticles, oxarticles.OXID, oxarticles.OXID=OLD.OXOBJECTID, product, U, 1]

    ongr_oxid.triggers.oxseo_data_delete.category:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcategories, oxcategories.OXID, oxcategories.OXID=OLD.OXOBJECTID, category, U, 1]

    ongr_oxid.triggers.oxseo_data_delete.content:
        class: %ongr_connections.sql_relations.table_relation.class%
        arguments: [oxcontents, oxcontents.OXID, oxcontents.OXID=OLD.OXOBJECTID, content, U, 1]

    # Seo data (`oxobject2seodata`) triggers
    ongr_oxid.triggers.oxseo_data_insert:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxobject2seodata, C]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_data_insert }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_update.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_update.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_update.content]]

    ongr_oxid.triggers.oxseo_data_update:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxobject2seodata, U, %ongr_oxid.triggers.seo_data.track_fields%]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_data_oxobjects_update }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_update.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_update.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_update.content]]

    ongr_oxid.triggers.oxseo_data_delete:
        class: %ongr_oxid.triggers.seo_trigger.class%
        arguments: [oxobject2seodata, D]
        tags:
          - { name: ongr_connections.trigger, trigger: oxseo_data_delete }
        calls:
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_delete.articles]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_delete.category]]
          - [addStatement, [@ongr_oxid.triggers.oxseo_data_delete.content]]
